# Generated by Django 6.0 on 2025-12-23 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamnesisQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('question_text', models.TextField()),
                ('input_type', models.CharField(default='single_choice', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pergunta da Anamnese',
            },
        ),
        migrations.CreateModel(
            name='AnamnesisOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('logic_metadata', models.JSONField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.anamnesisquestions')),
            ],
            options={
                'verbose_name': 'Opção da Anamnese',
            },
        ),
        migrations.CreateModel(
            name='AnamnesisSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('ai_score_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão da Anamnese',
            },
        ),
        migrations.CreateModel(
            name='AnamnesisAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('answer_value', models.TextField(blank=True, null=True)),
                ('is_red_flag', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.anamnesissessions')),
            ],
            options={
                'verbose_name': 'Resposta da Anamnese',
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('meeting_link', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to='accounts.doctors')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to='accounts.patients')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=255)),
                ('taken_at', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patients')),
            ],
            options={
                'verbose_name': 'Foto de Evolução',
            },
        ),
    ]
