# Generated by Django 6.0 on 2026-01-12 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='doctor_profile',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='patient_profile',
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('completed', 'Realizado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='appointments',
            constraint=models.UniqueConstraint(fields=('doctor', 'scheduled_at'), name='unique_doctor_slot'),
        ),
    ]
