# Generated by Django 6.0 on 2026-01-16 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_customer_id_mp'),
        ('medical', '0002_remove_appointments_doctor_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientphotos',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='patientphotos',
            name='photo',
            field=models.ImageField(default='', upload_to='evolution_gallery/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientphotos',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.patients'),
        ),
    ]
