# Generated by Django 6.0 on 2026-02-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctors_bio'),
        ('medical', '0003_remove_patientphotos_photo_url_patientphotos_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.doctors')),
            ],
            options={
                'verbose_name': 'Disponibilidade Médica',
                'verbose_name_plural': 'Disponibilidades Médicas',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
