# Generated by Django 6.0 on 2026-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_doctoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('completed', 'Realizado'), ('cancelled', 'Cancelado'), ('waiting_payment', 'Aguardando Pagamento')], default='scheduled', max_length=20),
        ),
    ]
