# Generated by Django 6.0.2 on 2026-03-03 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Anotações gerais e evolução clínica da consulta', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='consultation_end',
            field=models.DateTimeField(blank=True, help_text='Data/hora real do TÉRMINO do atendimento', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='consultation_start',
            field=models.DateTimeField(blank=True, help_text='Data/hora real do INÍCIO do atendimento', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='daily_doctor_token',
            field=models.TextField(blank=True, help_text='Token de acesso do Médico (Owner)', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='daily_patient_token',
            field=models.TextField(blank=True, help_text='Token de acesso do Paciente (Visitante)', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='daily_room_name',
            field=models.CharField(blank=True, help_text='Nome da sala privada no Daily.co', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='exam_request_data',
            field=models.JSONField(blank=True, help_text='Dados estruturados do Pedido de Exames', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='prescription_data',
            field=models.JSONField(blank=True, help_text='Dados estruturados do Receituário de Medicamentos', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
