# Generated by Django 6.0.2 on 2026-03-03 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Anotações gerais e evolução clínica da consulta', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='consultation_end',
            field=models.DateTimeField(blank=True, help_text='Data/hora real do TÉRMINO do atendimento', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='consultation_start',
            field=models.DateTimeField(blank=True, help_text='Data/hora real do INÍCIO do atendimento', null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='appointments',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
                    preserve_default=False,
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='medical_appointments' AND column_name='created_at') THEN
                            ALTER TABLE medical_appointments ADD COLUMN created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="ALTER TABLE medical_appointments DROP COLUMN IF EXISTS created_at;"
                )
            ]
        ),
        migrations.AddField(
            model_name='appointments',
            name='daily_doctor_token',
            field=models.TextField(blank=True, help_text='Token de acesso do Médico (Owner)', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='daily_patient_token',
            field=models.TextField(blank=True, help_text='Token de acesso do Paciente (Visitante)', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='daily_room_name',
            field=models.CharField(blank=True, help_text='Nome da sala privada no Daily.co', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='exam_request_data',
            field=models.JSONField(blank=True, help_text='Dados estruturados do Pedido de Exames', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='prescription_data',
            field=models.JSONField(blank=True, help_text='Dados estruturados do Receituário de Medicamentos', null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='appointments',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='medical_appointments' AND column_name='updated_at') THEN
                            ALTER TABLE medical_appointments ADD COLUMN updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="ALTER TABLE medical_appointments DROP COLUMN IF EXISTS updated_at;"
                )
            ]
        ),
    ]
