# Generated by Django 6.0 on 2026-03-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_appointments_clinical_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='daily_doctor_token',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='daily_patient_token',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='daily_room_name',
        ),
    ]
