# Generated by Django 6.0 on 2025-12-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('ticket', 'Boleto'), ('bank_transfer', 'Pix'), ('wallet_purchase', 'Crédito MP'), ('unknown', 'Desconhecido')], default='unknown', max_length=20),
        ),
    ]
