# Generated by Django 6.0 on 2026-01-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_transaction_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('ticket', 'Boleto'), ('bank_transfer', 'Pix'), ('wallet_purchase', 'Crédito MP'), ('unknown', 'Desconhecido')], default='unknown', max_length=20),
        ),
    ]
