# Generated by Django 6.0 on 2026-01-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_transaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription_id',
            field=models.CharField(blank=True, help_text='ID da Assinatura (Preapproval) no MP', max_length=100, null=True),
        ),
    ]
