# Generated by Django 6.0 on 2026-01-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_transaction_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bitrix_deal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bitrix_sync_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bitrix_sync_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mp_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
