# Generated by Django 6.0 on 2026-01-28 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_transaction_bitrix_deal_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código do cupom (ex: VERAO2026)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentagem (%)'), ('fixed', 'Valor Fixo (R$)')], default='fixed', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor do desconto (em R$ ou %)', max_digits=10)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Válido a partir de')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Limite global (vazio = ilimitado)', null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Limite por usuário (CPF)')),
                ('min_purchase_value', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo', max_digits=10)),
                ('current_uses', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor economizado', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.coupon'),
        ),
    ]
