# Generated by Django 6.0 on 2026-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_coupon_transaction_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor Efetivamente Pago', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Valor Original (Sugerido)', max_digits=10),
        ),
    ]
