# Generated by Django 6.0 on 2026-01-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_transaction_paid_amount_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='asaas_payment_id',
            field=models.CharField(blank=True, help_text='ID do Pagamento no Asaas', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='asaas_subscription_id',
            field=models.CharField(blank=True, help_text='ID da Assinatura no Asaas', max_length=100, null=True),
        ),
    ]
