# Generated by Django 6.0 on 2026-01-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_transaction_asaas_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cycle',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('one_off', 'Pagamento Único')], default='monthly', max_length=20),
        ),
    ]
