# Generated by Django 6.0 on 2026-03-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_alter_transaction_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='mercado_pago_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mp_metadata',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='subscription_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('ticket', 'Boleto'), ('bank_transfer', 'Pix'), ('unknown', 'Desconhecido')], default='unknown', max_length=20),
        ),
    ]
