# Generated by Django 6.0 on 2026-01-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id_mp',
            field=models.CharField(blank=True, help_text='ID do Cliente no Mercado Pago', max_length=50, null=True),
        ),
    ]
