# Generated by Django 6.0 on 2026-01-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_cep_user_city_user_complement_user_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asaas_customer_id',
            field=models.CharField(blank=True, help_text='ID do Cliente no Asaas', max_length=50, null=True),
        ),
    ]
