# Generated by Django 6.0 on 2026-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_asaas_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_valid_until',
            field=models.DateTimeField(blank=True, help_text='Data até quando o usuário mantém acesso após cancelar', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Motivo do cancelamento informado pelo usuário', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scheduled_cancellation_date',
            field=models.DateTimeField(blank=True, help_text='Data efetiva para corte do serviço', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Ativo'), ('past_due', 'Atrasado'), ('canceled', 'Cancelado'), ('grace_period', 'Cancelamento Agendado')], default='active', max_length=20),
        ),
    ]
