# Generated by Django 6.0 on 2026-01-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_access_valid_until_user_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scheduled_plan',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('plus', 'Plus'), ('none', 'Nenhum')], help_text='Plano agendado para a próxima renovação.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scheduled_transition_date',
            field=models.DateField(blank=True, help_text='Data prevista para a troca de plano.', null=True),
        ),
    ]
