# Generated by Django 6.0 on 2026-02-05 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_scheduled_plan_user_scheduled_transition_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de convite (Ex: DOC-X92A)', max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.OneToOneField(blank=True, help_text='Médico que utilizou este convite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_used', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
