# Generated by Django 6.0 on 2026-02-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_doctorinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
    ]
