# Generated by Django 6.0 on 2026-02-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_doctors_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='specialty_type',
            field=models.CharField(choices=[('trichologist', 'Tricologista'), ('nutritionist', 'Nutricionista')], default='trichologist', max_length=20),
        ),
        migrations.AddField(
            model_name='patients',
            name='assigned_nutritionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_patients', to='accounts.doctors'),
        ),
        migrations.AddField(
            model_name='patients',
            name='assigned_trichologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trichology_patients', to='accounts.doctors'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_patients', to='accounts.doctors'),
        ),
    ]
