# Generated by Django 6.0 on 2026-02-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_doctors_specialty_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='bio',
            field=models.TextField(blank=True, help_text='Descrição curta ou mini-currículo do profissional.', null=True),
        ),
    ]
