# Generated by Django 6.0.2 on 2026-03-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='Cadastro de Pessoa Física', max_length=14, null=True, unique=True),
        ),
    ]
