# Generated by Django 6.0 on 2026-03-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='assigned_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customer_id_mp',
        ),
    ]
